### ISSUE TITLE
How can I delete a migration file from the DB folder if the content is not added in the schema.rb file ?

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#16]
The rails db:migration aborted for the 20200126195938_add_reset_to_users.rb file . So I want to delete it. Is there any command or I can simple delete it? 
![ss](https://user-images.githubusercontent.com/19534210/73281620-7489eb00-421a-11ea-8d97-8285303514e5.png)

**Comment by sadmanahmed** [comment]
```
sample_app git:(password-reset) ✗ rails db:migrate:status

database: sample_app_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20191023203742  Create users
   up     20191024192018  Add index to users email
   up     20191026124751  Add password digest to users
   up     20191129205242  Add remember digest to users
   up     20191212201748  Add admin to users
   up     20191216192313  Add activation to users
   up     20200126193145  ********** NO FILE **********
  down    20200126195938  Add reset to users
```

**Comment by wasifhossain** [comment]
easiest way to **revert** a change made by some rails generator is to use `rails destroy`: https://guides.rubyonrails.org/command_line.html#rails-destroy

in Rails, generators are scripts that can run arbitrary commands. they are mainly used to scaffold templates for quick start.

in case there are some changes made by some generators that are NOT intended, simply run the same generator command, but with `destroy` or `d` instead of `generate` or `g`

.e.g. for your case, it would be: `rails d migration add_reset_to_users`
