### ISSUE TITLE
How to connect an mobile app with my ROR based website server?

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#22]
We are trying to make a website+app for a project and our website + app(flutter based) is almost ready ,but my website is on ruby on rails,databse on postgresql and hosted site is on heroku. How can I connect my website with the app?

**Comment by wasifhossain** [comment]
create api endpoints on the rails app, which the android app would consume

**Comment by sadmanahmed** [comment]
Can I get any helping tutorial ?

**Comment by wasifhossain** [comment]
you could post a new issue with the endpoint details. I will take a look and suggest next steps.

for the time being, you may take a look at this tutorial: https://blog.codeship.com/building-a-json-api-with-rails-5/
(this article would eventually use a gem for serialization - [ActiveModelSerializers](https://rubygems.org/gems/active_model_serializers), shortly called AMS - where I am a maintainer since 2019)

official rails guide to build api using Rails: https://guides.rubyonrails.org/api_app.html
