### ISSUE TITLE
How to solve syntex error while passing arguments to methods

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#24]
In my tutorials they add _class_, _placeholder_, _autofocus_ value  after _f.text_field :title_
Shown in (ss) in **line 18**
![Screenshot from 2020-02-23 19-11-35](https://user-images.githubusercontent.com/33208962/75112808-a8b5c780-5671-11ea-92af-5b11a40036a8.png)

After that the outlook they gain is (ss)
****Title** part changed**
![Screenshot from 2020-02-23 19-12-56](https://user-images.githubusercontent.com/33208962/75112822-e0bd0a80-5671-11ea-8535-dc19cd8da55c.png)

But when i am adding 

> class

 or anything after _f.text_field :title._ **It didn't work.** 
Here is (SS) **line 18**
![Screenshot from 2020-02-23 19-14-32](https://user-images.githubusercontent.com/33208962/75112857-532dea80-5672-11ea-9712-900e9ef3fee3.png)

**_Below error message shown after running the program (ss)_**
![Screenshot from 2020-02-23 19-15-23](https://user-images.githubusercontent.com/33208962/75112886-ac961980-5672-11ea-941d-ac58e5baec56.png)

**Comment by wasifhossain** [comment]
i can see the issue is related to how you are passing the argument to the `text_field` helper method.

the [`text_field` method](https://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-text_field) signature looks like:
```rb
text_field(method, options = {})
```
here `options` is a hash, so you can pass (key, value) pairs as arguments, which take the form as `key: value` (**look for the `:` after `key` instead of `=`**)

as an example, you may call the method as `f.text_field :title, class: "form-control"`

**Comment by ansary14-zz** [comment]
it worked.
