### ISSUE TITLE
why it is necessary to source a command whenever I reopen the terminal

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#5]
Every time, When I turn open the terminal. It's not finding the rails. And ruby updated version which I set up earliar. 
But *(Specific command)
**source /home/ayub/.rvm/scripts/rvm**
after this command its find the rails and ruby updated version.
![Screenshot from 2019-12-10 17-27-25](https://user-images.githubusercontent.com/33208962/70549438-69152e80-1b9e-11ea-98e8-704967ed3d92.png)
I have a bit of confusion that, why is it necessary to run this command whenever I reopen the terminal.
Any solution here...? Here I send a snapshot of my issue

**Comment by wasifhossain** [comment]
definitely! in fact, there is a good practice that everyone follows to handle the case.

the thing is, whenever we run a command in a shell, e.g. `rails`, the shell tries to look up `PATH` to find out the absolute path of the executable and runs it.

you can read the value of PATH by:
```sh
echo $PATH
```

besides, if your ruby gems are managed by tools like rvm/chruby/rbenv etc, then you need to add the path of these tools (that hosts all the gems) to the `PATH` environment variable.

for your case, the rvm bin path (`$HOME/.rvm/bin`) needs to be added to PATH.

the next question is, how to add the value to PATH so that the shell knows about it every time we run a new shell.

there is a rc file for each shell that we use, which you can find under the HOME directory (`echo $HOME`). these files have names based on the shell, e.g.
- .bashrc
- .zshrc
etc. 

to enable the shell to find out ruby gems managed by rvm, you need to add the rvm bin path in the rc file based on the current shell that are using.

```sh
echo $0
```
if the above command returns `bash`, then you need to add the following line at the end of `.bashrc`
```sh
export PATH="$PATH:$HOME/.rvm/bin"
```
this will add the rvm bin path at the end of the current PATH.

similarly, if the current shell is `zsh`, then the above line should be added to `.zshrc`.

now everytime you run any of these shells, it will be able to find the ruby gems from the current PATH.

**Comment by ansary14-zz** [comment]
I try to follow above instruction. But still I have same issue.
Here is my new screenshot.
![Screenshot from 2019-12-10 23-42-57](https://user-images.githubusercontent.com/33208962/70554318-1a1fc700-1ba7-11ea-84b6-f134d9a7374d.png)

**Comment by wasifhossain** [comment]
quoting from my post above
> you need to add the following line at the end of .bashrc
```sh
export PATH="$PATH:$HOME/.rvm/bin"
```

open .bashrc using any editor. lets use nano for the purpose
```sh
nano ~/.bashrc
```
then scroll to the bottom, paste the line, hit `ctrl + x` and `Y` to save it. After that, new shells should be able to find out the path

**Comment by ansary14-zz** [comment]
I have followed above instruction too yesterday. But my issue didn't solve
Here are some snapshot
![Screenshot from 2019-12-11 20-39-18](https://user-images.githubusercontent.com/33208962/70631163-f1efa100-1c56-11ea-973f-28d2640dc426.png)
![Screenshot from 2019-12-11 20-40-22](https://user-images.githubusercontent.com/33208962/70631165-f2883780-1c56-11ea-92cb-8bc4201259c2.png)
![Screenshot from 2019-12-11 20-41-14](https://user-images.githubusercontent.com/33208962/70631166-f2883780-1c56-11ea-98c3-199dfbf21c39.png)

**Comment by wasifhossain** [comment]
you dont need to edit .bashrc/.zshrc every time to include the rvm bin path. so you can remove all the duplicate lines containing `export PATH="$PATH:$HOME/.rvm/bin"` from the rc file

once you are done editing, can you open a new terminal and see if you can check the rails version: `rails -v`

**Comment by ansary14-zz** [comment]
after removing duplicate lines from rc file then
Open a new terminal. Enter below command
rails -v
same issue found.  command rails not found

**Comment by wasifhossain** [comment]
can you print the output of `echo $PATH`

**Comment by ansary14-zz** [comment]
here is my output
![Screenshot from 2019-12-11 21-48-13](https://user-images.githubusercontent.com/33208962/70636589-008e8600-1c60-11ea-81de-8cb8384d0f5d.png)

**Comment by wasifhossain** [comment]
also the output of the following commands please?
* `gem list rails`
* `rvm list`
* `rvm which rails`

**Comment by ansary14-zz** [comment]
after passing above command : 
![Screenshot from 2019-12-11 21-59-29](https://user-images.githubusercontent.com/33208962/70637532-9545b380-1c61-11ea-878c-066a64240b21.png)

**Comment by ansary14-zz** [comment]
After passing the **source command
![Screenshot from 2019-12-11 22-02-31](https://user-images.githubusercontent.com/33208962/70637861-287ee900-1c62-11ea-8f41-96fb03770388.png)
** before all 
Here is the new snapshot

**Comment by wasifhossain** [comment]
i see. the behaviour does not look usual.

by right-clicking on your current terminal, do you see any option like settings or preferences?

**Comment by ansary14-zz** [comment]
I see option which is **Preferences**

**Comment by wasifhossain** [comment]
can you open preferences and share a screenshot

**Comment by ansary14-zz** [comment]
![Screenshot from 2019-12-11 22-15-22](https://user-images.githubusercontent.com/33208962/70638840-c0310700-1c63-11ea-8647-033591119648.png)

**Comment by wasifhossain** [comment]
can you click on Global -> General and share another ss

**Comment by ansary14-zz** [comment]
![Screenshot from 2019-12-11 22-17-36](https://user-images.githubusercontent.com/33208962/70639023-0d14dd80-1c64-11ea-952b-9cea79c31400.png)

**Comment by wasifhossain** [comment]
okay can you please go back to previous select option 'Unnamed' and click on the 'Command' tab

**Comment by ansary14-zz** [comment]
![Screenshot from 2019-12-11 22-20-35](https://user-images.githubusercontent.com/33208962/70639288-7bf23680-1c64-11ea-81b0-146851febe15.png)

**Comment by wasifhossain** [comment]
lets check the 1st option: `Run command as a login shell`. After that, close the window, then open a new terminal and try the following again
* `gem list rails`
* `gem -v`

**Comment by ansary14-zz** [comment]
![Screenshot from 2019-12-11 22-24-57](https://user-images.githubusercontent.com/33208962/70639737-15b9e380-1c65-11ea-8699-f598b2b4a39e.png)

**Comment by wasifhossain** [comment]
it worked :tada: now you should be able to run any ruby gems on a new terminal without **sourcing** the rvm script every time!

you may close the issue if it solves your case

**Comment by ansary14-zz** [comment]
Solved. Finally
