### ISSUE TITLE
capitalize vs capitalize!: regular vs bang method

### ISSUE THREAD

**Issue by ahadrajnomore** [ormprog/rails_ama#84]
Why my first name and last name is not showing in console? do I have to do a another line for using exclamation mark ?

![image](https://user-images.githubusercontent.com/64307256/85597799-c3726a00-b66c-11ea-8a9d-d5369a0ded07.png)

**Comment by wasifhossain** [comment]
The reason lies in the [`capitalize!`](https://ruby-doc.org/core-2.7.1/String.html#method-i-capitalize-21) method description.

> Returns `nil` if no changes are made

as you have already entered the first and last names in capital letters, calling `.capitalize!` returned `nil` due to no change being made and assigned to `a1` and `a2`, which is why you don't see any output for the first and last names in the last line

#### Let's talk about some background

An important point in Ruby is, there are many methods that might come in `bang` version besides `regular` one.

e.g. `capitalize` is a regular method, while `capitalize!` is the bang version (note the exclamation `!` after the method)

the specialty of a bang method is, they change the value of the receiver **in place**, while a regular method clones the original value first, then changes the clone and finally returns.


to clarify,
```rb
first_name.capitalize!
```
here `first_name` is the **receiver** or **caller** of the `capitalize!` method

Let's see an example

```rb
a = 'hello'
b = a.capitalize
puts a # hello <----- original value didn't change
puts b # Hello 

c = 'world'
d = c.capitalize!
puts c # World <----- original value changed
puts d # World
```

#### Standard practice is to `use the regular version is most cases`, while you should use the bang version of a method with great care only if you know the internals (like what the method returns in different cases).

Let me know if you like to have more clarifications

**Comment by ahadrajnomore** [comment]
Thank you.  You made it crystal clear. 😊

**Comment by wasifhossain** [comment]
feel free to **reopen** the issue if you still have any questions
